// Generated by 'unplugin-auto-import'
export {}
declare global {
  const dependsLuminanceColor: typeof import('../utils/dependsLuminanceColor')['dependsLuminanceColor']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly dependsLuminanceColor: UnwrapRef<typeof import('../utils/dependsLuminanceColor')['dependsLuminanceColor']>
  }
}
