// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomNavigationBar: typeof import('./../../components/layouts/BottomNavigationBar/BottomNavigationBar.vue')['default']
    Button: typeof import('./../../components/utils/Button/Button.vue')['default']
    Chart: typeof import('./../../components/utils/Chart/Chart.vue')['default']
    Header: typeof import('./../../components/layouts/Header/Header.vue')['default']
    Icon: typeof import('./../../components/utils/Icon/Icon.vue')['default']
    NavgationBar: typeof import('./../../components/layouts/NavigationBar/NavgationBar.vue')['default']
    NavigationBar: typeof import('./../../components/layouts/NavigationBar/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInButton: typeof import('./../../components/utils/SignInButton/SignInButton.vue')['default']
    Tab: typeof import('./../../components/utils/Tab/Tab.vue')['default']
  }
}
