// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useColorStore: typeof import('../../composables/style/colorStore')['useColorStore']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly useColorStore: UnwrapRef<typeof import('../../composables/style/colorStore')['useColorStore']>
  }
}
