// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useAuthStore: typeof import('../../composables/firebase/authStore')['useAuthStore']
  const useColorStore: typeof import('../../composables/style/colorStore')['useColorStore']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly useAuthStore: UnwrapRef<typeof import('../../composables/firebase/authStore')['useAuthStore']>
    readonly useColorStore: UnwrapRef<typeof import('../../composables/style/colorStore')['useColorStore']>
  }
}
