// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useAccessibleHardwareIdsStore: typeof import('../../composables/firebase/accessibleHardwareIdsStore')['useAccessibleHardwareIdsStore']
  const useAuthStore: typeof import('../../composables/firebase/authStore')['useAuthStore']
  const useColorStore: typeof import('../../composables/style/colorStore')['useColorStore']
  const useSensingDataStore: typeof import('../../composables/firebase/sensingDataStore')['useSensingDataStore']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly useAccessibleHardwareIdsStore: UnwrapRef<typeof import('../../composables/firebase/accessibleHardwareIdsStore')['useAccessibleHardwareIdsStore']>
    readonly useAuthStore: UnwrapRef<typeof import('../../composables/firebase/authStore')['useAuthStore']>
    readonly useColorStore: UnwrapRef<typeof import('../../composables/style/colorStore')['useColorStore']>
    readonly useSensingDataStore: UnwrapRef<typeof import('../../composables/firebase/sensingDataStore')['useSensingDataStore']>
  }
}
