// Generated by 'unplugin-auto-import'
export {}
declare global {
  const dependsLuminanceColor: typeof import('../../utils/style/dependsLuminanceColor')['dependsLuminanceColor']
  const displayType: typeof import('../../utils/utils/displayType')['displayType']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly dependsLuminanceColor: UnwrapRef<typeof import('../../utils/style/dependsLuminanceColor')['dependsLuminanceColor']>
    readonly displayType: UnwrapRef<typeof import('../../utils/utils/displayType')['displayType']>
  }
}
